environment:
    type: "Abides"
gamma: 0.995
lamda: 0.97
updates: 50
epochs: 4
n_workers: 16
worker_steps: 256
n_mini_batch: 4
value_loss_coefficient: 0.25
hidden_layer_size: 128
max_grad_norm: 0.3
recurrence: 
    sequence_length: 8
    hidden_state_size: 64
    layer_type: lstm
    reset_hidden_state: True
learning_rate_schedule:
    initial: 3.0e-4
    final: 1.0e-5
    power: 1.0
    max_decay_steps: 100
beta_schedule:
    initial: 0.0005
    final: 0.00005
    power: 1.0
    max_decay_steps: 100
clip_range_schedule:
    initial: 0.2
    final: 0.15
    power: 1.0
    max_decay_steps: 500