environment:
    type: "Abides"
    starting_cash: 10000000
    timestep_duration: "5S"
    order_fixed_size: 20
    execution_window: "00:30:00"
    parent_order_size: 10000
    debug_mode: True
gamma: 0.99
lamda: 0.98
updates: 151
epochs: 6
n_workers: 12
worker_steps: 360
n_mini_batch: 4
value_loss_coefficient: 0.5
hidden_layer_size: 128
max_grad_norm: 0.5
recurrence: 
    sequence_length: 128
    hidden_state_size: 256
    layer_type: lstm
    reset_hidden_state: True
learning_rate_schedule:
    initial: 5.0e-4
    final: 3.0e-6
    power: 1.0
    max_decay_steps: 100
beta_schedule:
    initial: 0.01
    final: 0.0001
    power: 1.0
    max_decay_steps: 100
clip_range_schedule:
    initial: 0.2
    final: 0.1
    power: 1.0
    max_decay_steps: 1000