agent: 
  name: "RPPO" 
  config_path: "/Users/alexst-aubin/Library/CloudStorage/GoogleDrive-alex.staubin2@gmail.com/My Drive/McGill/McGill_Winter25/COMP579/FinalProject/code/src/oterl/configs/abides.yaml"
timesteps:
  - 500000
  - 1000000
  - 2000000
seed: 0
