agent: 
  name: "RPPO" 
  config_path: "/Users/jonathancampies/Desktop/Comp579FinalProject/COMP579_Final_Project/src/oterl/agents/recurrent_ppo_truncated_bptt/configs/abides.yaml"
timesteps:
  - 500000
  - 1000000
  - 2000000
seed: 0
